kind: Application
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: application2
  namespace: 3scale-dev
spec:
  accountCR:
    name: developeraccount2
  applicationPlanName: plan01
  description: 'testing application'
  name: testApp
  productCR:
    name: product2
  suspend: false