apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: developeruser-admin-sample
  namespace: 3scale-dev
spec:
  developerAccountRef:
    name: developeraccount1
  email: myusername2@example.com
  passwordCredentialsRef:
    name: myusername02
  role: admin
  username: myusername02