apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: developeruser02
  namespace: 3scale-dev
spec:
  username: myusername02
  email: myusername02example.com
  passwordCredentialsRef:
    name: myusername02
  role: admin
  developerAccountRef:
    name: developeraccount2